CREATE TABLE STUDENT(
  SID INT PRIMARY KEY,
  S_NAME VARCHAR(30)
);

INSERT INTO STUDENT values(1 , 'AMAL');
INSERT INTO STUDENT values(2 , 'ANIKET');
INSERT INTO STUDENT values(3 , 'ABHISHEK');

select * FROM STUDENT;
