-- Creating the STUDENT table
CREATE TABLE STUDENT(
  SID INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,  
  LOCATION VARCHAR(50), 
  EMAIL VARCHAR(100) UNIQUE,
  AGE INT CHECK(AGE >= 18)
);

-- Creating the COURSE table
CREATE TABLE COURSE(
  CID INT PRIMARY KEY,
  CNAME VARCHAR(50) NOT NULL,  
  STUDENT_ID INT,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(SID)
);

-- Insert students first (to satisfy the foreign key constraint)
INSERT INTO STUDENT (SID, NAME, LOCATION, EMAIL, AGE) 
VALUES (1, 'ANIKET', 'NOIDA', 'ANIKETSHISODIA7@GMAIL.COM', 23);

INSERT INTO STUDENT (SID, NAME, LOCATION, EMAIL, AGE) 
VALUES (2, 'AMAL', 'NOIDA', 'AMAL@GMAIL.COM', 20);  -- Added AGE to avoid constraint error

-- Now insert into the COURSE table
INSERT INTO COURSE(CID, CNAME, STUDENT_ID)
VALUES (100, 'DSA', 1);

-- Retrieve data
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
